#!/bin/bash

cd "$(dirname "$(readlink -f "$0")")"
source venv/bin/activate

case "$OSTYPE" in
    darwin*) gunicorn -c server.g_conf.py ;;
    linux*) authbind gunicorn -c server.g_conf.py ;;
    *) echo "unsupported OS - server not started" && exit 0 ;;
esac
# python -m src.server.canvas &