#!/bin/bash

cd "$(dirname "$(readlink -f "$0")")"

PID_FILE="pid_bambu_printers"
STOP_FILE="common/SPECIAL_BAMBU_STOP"

if [ ! -f $PID_FILE ]; then
    echo "bambu_printers is not running"
    exit 1
fi

touch $STOP_FILE
rm $PID_FILE