#!/bin/bash

cd "$(dirname "$(readlink -f "$0")")"

PID_FILE="pid_bambu_printers"

if [ ! -f $PID_FILE ]; then
    echo "bambu_printers is not running"
    exit 1
fi

touch common/SPECIAL_BAMBU_STOP
rm $PID_FILE