READER_ONLINE = 1
READER_OFFLINE = 0

ALARM_ENABLE = 1
ALARM_DISABLE = 0

ALARM_STATUS_OK = 0
ALARM_STATUS_ALARM = 1
ALARM_STATUS_TAGGEDOUT = 2
ALARM_STATUS_DISABLED = 3

CANVAS_OK = 0
CANVAS_UPDATING = 1
CANVAS_PENDING = 2

ACCESS_NO = 0
ACCESS_YES = 1
ACCESS_NO_OVERRIDE = 2
ACCESS_YES_OVERRIDE = 3

NEVER = -1

UID_LEN = 8

PRINT_EXPIRED = 0
PRINT_SUCCEEDED = 1
PRINT_FAILED = 2
PRINT_CANCELED = 3

NO_FORM_ROW = -1
NO_PRINT_ID = -1
NO_CRUZID = ""

BAMBU_TIMEOUT = 10 * 60
BAMBU_DEFAULT_LIMIT = 1000
BAMBU_DELAY = 10

BAMBU_FAILED = 0
BAMBU_RUNNING = 1
BAMBU_PAUSE = 2
BAMBU_IDLE = 3
BAMBU_FINISH = 4
BAMBU_UNKNOWN = 5